/*
 * Simulator.java
 *
 * Created on 15 de septiembre de 2005, 15:34
 */

package presentation.display;

import java.awt.Component;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JPanel;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author  jeronimo
 */
public class Simulator extends javax.swing.JFrame {
    
   private Map paneles;
   private static Simulator inst = null;
    /**
     * Creates new form Simulator
     */
    private Simulator() {
        initComponents();
        setBounds(0,0, 1024,768);
        this.setTitle("ATM SIMULATOR 1.0.1");
        paneles = new HashMap();
        paneles.put(new Integer(1),jPanel1);
        paneles.put(new Integer(2),jPanel2);
        paneles.put(new Integer(3),jPanel3);
        paneles.put(new Integer(4),jPanel4);
        paneles.put(new Integer(5),jPanel5);
        jEditorPane1.setContentType("text/html");
        jEditorPane1.setEditable(false);
        ((AbstractDocument)jEditorPane1.getDocument()).setAsynchronousLoadPriority(-1);
    }
    
    public static Simulator getInstance()
    {
        if(inst == null)
            inst = new Simulator();
        return inst;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 15, true));
        jPanel1.setForeground(java.awt.SystemColor.controlDkShadow);
        jPanel1.setMaximumSize(new java.awt.Dimension(640, 480));
        jPanel1.setMinimumSize(new java.awt.Dimension(640, 480));
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 480));
        jLayeredPane1.setMaximumSize(new java.awt.Dimension(2500, 2000));
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(2500, 2000));
        jLayeredPane1.setOpaque(true);
        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(640, 480));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(640, 480));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(640, 480));
        jEditorPane1.setBorder(null);
        jEditorPane1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jEditorPane1.setMaximumSize(new java.awt.Dimension(640, 480));
        jEditorPane1.setMinimumSize(new java.awt.Dimension(640, 480));
        jEditorPane1.setPreferredSize(new java.awt.Dimension(640, 480));
        jScrollPane1.setViewportView(jEditorPane1);

        jScrollPane1.setBounds(0, 0, 640, 480);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jLayeredPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 1, true));
        jPanel2.setMaximumSize(new java.awt.Dimension(344, 288));
        jPanel2.setMinimumSize(new java.awt.Dimension(344, 288));
        jPanel2.setPreferredSize(new java.awt.Dimension(344, 288));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 120;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 1, true));
        jPanel3.setMaximumSize(new java.awt.Dimension(320, 240));
        jPanel3.setMinimumSize(new java.awt.Dimension(320, 240));
        jPanel3.setPreferredSize(new java.awt.Dimension(320, 240));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 120;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel3, gridBagConstraints);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 1, true));
        jPanel4.setMaximumSize(new java.awt.Dimension(320, 240));
        jPanel4.setMinimumSize(new java.awt.Dimension(320, 240));
        jPanel4.setPreferredSize(new java.awt.Dimension(320, 240));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 120;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel4, gridBagConstraints);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        jPanel5.setMaximumSize(new java.awt.Dimension(344, 480));
        jPanel5.setMinimumSize(new java.awt.Dimension(344, 480));
        jPanel5.setPreferredSize(new java.awt.Dimension(344, 480));
        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("cfg\\resources\\LogoMediumSize.jpg"));
        jPanel5.add(jLabel1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel5, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void setComponentOnPanel(int i,Component c) throws Exception
    {
        JPanel jp = (JPanel)paneles.get(new Integer(i));
        jp.removeAll();
        jp.add(c, java.awt.BorderLayout.CENTER);
    }
    
    public javax.swing.JEditorPane getEditorPane()
    {
        return jEditorPane1;
    }
    
    public JPanel getPanel(int i)
    {
        return (JPanel)paneles.get(new Integer(i));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulator().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
