/*
 * ListSelectionDialog.java
 *
 * Created on 2 de enero de 2006, 22:18
 */
 
package tools.stateeditor.graphics;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author  jeronimo
 */
public class ListSelectionDialog extends javax.swing.JDialog {
    
    /** Creates new form ListSelectionDialog */
    private DefaultListModel dm;
    private DefaultListModel dm2;
    private HashMap map;
    private boolean ok;
    public ListSelectionDialog(java.awt.Frame parent,String title, boolean modal, HashMap mapo, Vector tri) {
        super(parent, title, modal);
        ok= false;
        dm = new DefaultListModel();
        dm2 = new DefaultListModel();
        map = mapo;
        Iterator it = map.keySet().iterator();
        while(it.hasNext())
        {
            dm.addElement(it.next());
        }
        it = tri.iterator();
        while(it.hasNext())
        {
            dm2.addElement(it.next());
        }
        initComponents();
    }
    
    public boolean isOk()
    {
        return ok;
    }
    
    public Vector getSelectedValues()
    {
        DefaultListModel dl = (DefaultListModel)selectedItems.getModel();
        Vector vec = new Vector();
        for(int i=0;i<dl.size();i++)
        {
            vec.add(map.get(dl.getElementAt(i)));
        }
        System.out.println(vec);
        return vec;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        posibleItemsSP = new javax.swing.JScrollPane();
        posibleItems = posibleItems = new JList(dm);
        selectedItemsSP = new javax.swing.JScrollPane();
        selectedItems = selectedItems = new JList(dm2);
        ButAgregar = new javax.swing.JButton();
        ButRemover = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        posibleItemsSP.setViewportView(posibleItems);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        getContentPane().add(posibleItemsSP, gridBagConstraints);

        selectedItemsSP.setViewportView(selectedItems);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 5);
        getContentPane().add(selectedItemsSP, gridBagConstraints);

        ButAgregar.setText(">>");
        ButAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAgregarActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 5, 0, 0);
        getContentPane().add(ButAgregar, gridBagConstraints);

        ButRemover.setText("<<");
        ButRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButRemoverActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 5, 0, 0);
        getContentPane().add(ButRemover, gridBagConstraints);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(30, 20, 17, 0);
        getContentPane().add(btnAceptar, gridBagConstraints);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 9, 17, 20);
        getContentPane().add(btnCancelar, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
// TODO add your handling code here:
        ok = false;
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
// TODO add your handling code here:
        ok = true;
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void ButRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButRemoverActionPerformed
// TODO add your handling code here:
        if(selectedItems.getSelectedIndex()!=-1)
        {
            Object o = selectedItems.getSelectedValue();
            ((DefaultListModel)posibleItems.getModel()).addElement(o);
            ((DefaultListModel)selectedItems.getModel()).removeElement(o);
        }
    }//GEN-LAST:event_ButRemoverActionPerformed

    private void ButAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAgregarActionPerformed
    // TODO add your handling code here:
        if(posibleItems.getSelectedIndex()!=-1)
        {
            Object o = posibleItems.getSelectedValue();
            ((DefaultListModel)selectedItems.getModel()).addElement(o);
            ((DefaultListModel)posibleItems.getModel()).removeElement(o);            
        }
    }//GEN-LAST:event_ButAgregarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new ListSelectionDialog(new javax.swing.JFrame(), true,  new HashMap()).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButAgregar;
    private javax.swing.JButton ButRemover;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JList posibleItems;
    private javax.swing.JScrollPane posibleItemsSP;
    private javax.swing.JList selectedItems;
    private javax.swing.JScrollPane selectedItemsSP;
    // End of variables declaration//GEN-END:variables
    
}
